return require('packer').startup(function()
    use 'wbthomason/packer.nvim'
    use 'tmhedberg/SimpylFold'
    use 'kyazdani42/nvim-tree.lua'
    use 'godlygeek/tabular'
    use 'majutsushi/tagbar'
    use 'scrooloose/nerdcommenter'
    use 'nvie/vim-flake8'
    use 'tpope/vim-abolish'
    use 'p00f/nvim-ts-rainbow'
    use 'JuliaEditorSupport/julia-vim'
    use 'stevearc/vim-arduino'
    use 'vim-test/vim-test'
    use {
        'nvim-telescope/telescope.nvim',
         requires = {{'nvim-lua/popup.nvim'}, {'nvim-lua/plenary.nvim'}}
    }
    use 'sharkdp/bat'
    use 'sharkdp/fd'
    use 'BurntSushi/ripgrep'
    use 'nvim-treesitter/nvim-treesitter'
    use 'neovim/nvim-lspconfig'
    use 'kyazdani42/nvim-web-devicons'
    use 'kabouzeid/nvim-lspinstall'
    use 'hrsh7th/nvim-compe'
    use 'kyazdani42/nvim-web-devicons'
    use 'tpope/vim-commentary'
    use 'voldikss/vim-floaterm'
    use 'windwp/nvim-autopairs'
    use 'easymotion/vim-easymotion'
    use 'karb94/neoscroll.nvim'
    use 'glepnir/indent-guides.nvim'
    use 'glepnir/lspsaga.nvim'
    use 'onsails/lspkind-nvim'
    use 'akinsho/nvim-bufferline.lua'
    use 'hoob3rt/lualine.nvim'
    use 'hrsh7th/vim-vsnip'
    use 'simrat39/symbols-outline.nvim'
end)
